title: zarahzachz
# email: your-email@domain.com
# description: > # this means to ignore newlines until "baseurl:"
#     Write an awesome description for your new site here.
#     You can edit this line in _config.yml. It will appear
#     in your document head meta (for Google search results)
#     and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://zarahzachz.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  zarahzachz

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%d-%b-%y'

collections:
  tags:
    output: true

defaults:
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "base"